      - name: Clean Buildozer Cache & Android Platform
        run: |
          rm -rf ~/.buildozer
          rm -rf .buildozer/
          buildozer android clean || true

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: smart-finder-apk
          path: bin/*.apk
          if-no-files-found: error
